[package]
name = "fluistern-gui"
version = "0.2.0"
edition = "2021"

[[bin]]
name = "fluistern-gui"
path = "src/main.rs"

[dependencies]
slint = "1.9"
rusqlite = { version = "0.32", features = ["bundled"] }
chrono = "0.4"

[build-dependencies]
slint-build = "1.9"
